DROP TABLE IF EXISTS CATALOGITEM;
CREATE TABLE CATALOGITEM
(
    id    int AUTO_INCREMENT PRIMARY KEY,
    type  VARCHAR(50) NOT NULL,
    name  VARCHAR(50) NOT NULL,
    price DOUBLE (4
) NOT NULL,
amountLeft INTEGER (10) NOT NULL,
);


DROP TABLE IF EXISTS USER;
CREATE TABLE USER
(
    id    int AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    role  VARCHAR(50) NOT NULL,
    paymentMethod VARCHAR(50) NOT NULL
);




