DROP TABLE IF EXISTS AIRLINE;
CREATE TABLE AIRLINE (
id int AUTO_INCREMENT  PRIMARY KEY,
name VARCHAR(50) NOT NULL,
initialBudget BIGINT NOT NULL,
currentBudget BIGINT NOT NULL,
homeBaseId int NOT NULL
);